spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/microservice_trasportador?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
